### ISSUE TITLE
Pipeline commit message is not complete

### ISSUE THREAD

**Issue by ehennestad** [openMetadataInitiative/openMINDS#15]
The build workflows of the target repositories have the following code for creating a commit message:

```
git commit -m "build triggered by submodule ${{ inputs.repository }} version ${{ inputs.branch }}"
```

However the `inputs.repository` and `inputs.branch` variables are not added to the actual commit message, see for example :
https://github.com/openMetadataInitiative/openMINDS_JSON-Schema/commit/2628169cc48eaa69a020a93f9e9463e59d409077

**Comment by ehennestad** [comment]
Following up on this:

"Module" repositories, i.e `openMINDS_core` provides some [inputs](https://github.com/openMetadataInitiative/openMINDS_core/blob/e873947bd8cae1de08aebd3ecc59a1c81d218cb3/.github/workflows/openMINDS_upstream.yml#L13) (branch_name, repository_name) to the `build` action of `openMINDS/pipeline`.

The `build` action uses these inputs to create a [commit message](https://github.com/openMetadataInitiative/openMINDS/blob/aa7af49bf61e477c7c424e5e51ced57b2659864d/.github/workflows/build.yml#L53) like this:

> [build triggered by submodule openMetadataInitiative/openMINDS_stimulation version v1](https://github.com/openMetadataInitiative/openMINDS/commit/81e1f90e4e59fe13147a9169691f90a259734e42)

However, these input arguments are not propagated to any of the target repositories' `build` action (and I don't know if that is possible), but all the target repositories have the same command for pushing in their `build` action, i.e:

[`git commit -m "build triggered by submodule ${{ inputs.repository }} version ${{ inputs.branch }}"`](https://github.com/openMetadataInitiative/openMINDS_JSON-Schema/blob/16b522bb7136be61e82f5983f91a925bbe823bd0/.github/workflows/build.yml#L44)

**Comment by lzehl** [comment]
@olinux can we have a look at this together?

**Comment by Raphael-Gazzotti** [comment]
The issue might be due to missing required arguments for the workflow_dispatch trigger when compared with the working version. I'll open PRs to add these arguments.

```
    inputs:
      branch:
        description: 'The branch of the submodule the workflow was triggered for'
        required: true
        type: string
      repository:
        description: 'The repository of the submodule the workflow was triggered for'
        required: true
        type: string
```
